version: "3.8"

services:
  stats:
    image: docker-registry.groupclaes.be/groupclaes_web-api-stats
    environment:
      APP_VERSION: v1
      NODE_ENV: production
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.labels.worker == true]
      resources:
        reservations:
          memory: 20M
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.groweb-api-stats.rule=Host(`api.groupclaes.be`) && PathPrefix(`/v1/stats`)"
        - "traefik.http.routers.groweb-api-stats.entrypoints=web"
        - "traefik.http.services.groweb-api-stats.loadbalancer.server.port=80"
    configs:
      - source: groupclaes_web-api-stats
        target: /usr/src/app/config.js
    networks:
      - traefik_web
      - logging
      - default

configs:
  groupclaes_web-api-stats:
    external: true

networks:
  traefik_web:
    external: true
  logging:
    external: true
